/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.*;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    } //get rid

    public static void main(String[] args) throws IOException {

        //call method here
        System.out.println(new App().getGreeting()); //get rid
        fileScanner();
    }

    // method comes here dfghj
    public static void fileScanner() throws FileNotFoundException {
        Scanner readThru;
        try {
            readThru = new Scanner(new BufferedReader(new FileReader(new File("src/main/resource/text.txt"))));
            System.out.println("great");

            while(readThru.hasNext()){
              System.out.println("great");
}
        }
        catch (FileNotFoundException e) {
            System.out.println("File is not available");

        }
    }

}
