/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.*;
import java.util.Scanner;


public class App {
    public String getGreeting() {
        return "Hello my people.";
    }
    public static void main(String[] args) throws IOException {
//        System.out.println(new App().getGreeting()); //get rid
        File location = new File("src/main/resources/gate.js");
        fileScanner(location);
    }
    public static String fileScanner(File location){
        int lineCounter = 1;
        String answer = "";
        try {
            Scanner readThru = new Scanner(location);
            String nextLine;
//            System.out.println(location.length());

            while(readThru.hasNext()){
            nextLine = readThru.nextLine();
            boolean condition1 = nextLine.endsWith(";");
            boolean condition2 = nextLine.endsWith("{");
            boolean condition3 = nextLine.endsWith("}");
            boolean condition4 = nextLine.endsWith("if");
            boolean condition5 = nextLine.endsWith("else");
            boolean condition6 = nextLine.isBlank();
            if((!condition1) && !condition2 && !condition3 && !condition4 && !condition5 && !condition6){
//                System.out.println("Line " + lineCounter + " Missing semicolon");
                answer+= "Line " + lineCounter + " Missing semicolon\n";
            }
            lineCounter++;
        }
//            System.out.println(answer);

//            System.out.println("Done with this assignment");
        }
        catch (FileNotFoundException e) {
            System.out.println("File is not available");
        }
        return answer;
    }
}

